### ISSUE TITLE
How to understand `padding=35` for the first conv layer?

### ISSUE THREAD

**Issue by yang-jin-hai** [xwjabc/hed#18]
I also find this config in the original repo. I think it may be used to increase side outputs resolution, but why it's 35?

**Comment by yang-jin-hai** [comment]
I figure it out ^_^

**Comment by debvrat** [comment]
Hi, @WannaSeaU I have the same query. What is the reason behind padding=35 for the first conv layer? 

[meteorshowers](https://github.com/meteorshowers/hed/blob/master/models.py) also used padding = 21 for the first conv layer. Why is that? Shouldn't padding be equal to 1 for all the layers?

Also a query for @xwjabc
