### ISSUE TITLE
Question about eval.

### ISSUE THREAD

**Issue by AlbertTJU** [xwjabc/hed#20]
Thanks for your code！But I have a question, how to evaluate the result？I don't have any idea, thanks!

**Comment by xwjabc** [comment]
The quantitative evaluation is shown in the README.md, which can also be found below:
```
cd eval
(echo "data_dir = '../output/epoch-39-test'"; cat eval_edge.m)|matlab -nodisplay -nodesktop -nosplash
```
For qualitative evaluation, you can find out the generated png images in the output folders.

**Comment by AlbertTJU** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    谢谢！另外我还有一个问题，就是如果我想评价RCF的结果呢？这个统一的评价工具应该在哪里找到啊？ps：您应该是中国人吧Thank you! But I have another question, if I want to eval the results of RCF, what should I do? Thanks a lot!
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                395494013
                            
                    
                        
                            
                                    395494013@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 3/14/2020 07:46，Weijian Xu<notifications@github.com> wrote： 



The quantitative evaluation is shown in the README.md, which can also be found below:
cd eval
(echo "data_dir = '../output/epoch-39-test'"; cat eval_edge.m)|matlab -nodisplay -nodesktop -nosplash

For qualitative evaluation, you can find out the generated png images in the output folders.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xwjabc** [comment]
RCF and HED share the same quantitative evaluation methods: ODS and OIS score. You can use the evaluation script in this repo for the RCF evaluation.

**Comment by AlbertTJU** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Ok, thank you!
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                395494013
                            
                    
                        
                            
                                    395494013@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 3/15/2020 06:17，Weijian Xu<notifications@github.com> wrote： 



RCF and HED share the same quantitative evaluation methods: ODS and OIS score. You can use the evaluation script in this repo for the RCF evaluation.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by AlbertTJU** [comment]
> RCF and HED share the same quantitative evaluation methods: ODS and OIS score. You can use the evaluation script in this repo for the RCF evaluation.

Hello, I'm sorry to bother you, but when I add CBAM attention module in networks, there are some errors like this, and how to fix this? Thank you again!
![image](https://user-images.githubusercontent.com/44995970/77636201-b0c59780-6f8e-11ea-9258-c6a4466391d6.png)

**Comment by xwjabc** [comment]
Your network may have deeper nested parameters (due to the CBAM attention module). Please show net.named_parameters() and try to check the keys. You may need to modify the load_pretrained_caffe() to support your situation.

**Comment by AlbertTJU** [comment]
> Your network may have deeper nested parameters (due to the CBAM attention module). Please show net.named_parameters() and try to check the keys. You may need to modify the load_pretrained_caffe() to support your situation.
