### ISSUE TITLE
evaluation of edge result on NYUD dataset

### ISSUE THREAD

**Issue by rrryan2016** [xwjabc/hed#26]
Thanks for your great work and kind sharing. 

Have you ever test your model on NYU depth dataset? I came up against a problem in this step. 

I could not find the NYUD edge ground truth file after training on its training sets, could you please give me any advice? 

Thanks in advance.

**Comment by xwjabc** [comment]
Hi @rrryan2016, thank you for your interest in this repo! Unfortunately, I have only trained and evaluated my model on BSDS dataset. Perhaps you can refer to [RCF code base](https://github.com/yun-liu/RCF) for more details about NYUD dataset.

**Comment by rrryan2016** [comment]
Thanks for your kind reply. I found it in https://github.com/yun-liu/RCF/issues/87  :P
