### ISSUE TITLE
question about evaluate

### ISSUE THREAD

**Issue by Atomwh** [xwjabc/hed#3]
Hi！Thanks for sharing this code! When I run your evaluation code:

> python hed.py --checkpoint ./data/hed_checkpoint.pt --output ./output-mypretrain --test
cd eval
(echo "data_dir = '../output-mypretrain/test'"; cat eval_edge.m)|matlab -nodisplay -nodesktop -nosplash

I got this result:

> ODS=0.381 OIS=0.386 AP=0.176 R50=0.020 - HED

That's confusing.
Is there some bugs in evaluation code or  some considerations?
Thanks a lot.

**Comment by xwjabc** [comment]
It seems the result is so low in your case. I just uploaded a sample of generated edges for test images (https://cseweb.ucsd.edu/~weijian/static/datasets/hed/sample-test.tar). Could you download it and check if the edges match your generated ones?

**Comment by Atomwh** [comment]
Thank you very much for your reply ! I evaluate your generated edges and get:

> ODS=0.788 OIS=0.806 AP=0.809 R50=0.898 - HED

That's right and the evaluation code is correct. My generated egdes have some errors.
thank you very much !

**Comment by shuangshuangguo** [comment]
Hi! I have encountered a error in eval_edge.m line 28:
E=convTri(single(x),1);
The error said: Conversion to single from cell is not possible. 

Do you have faced the same problem? It seems that x is a cell and can not be transformed to single.
