### ISSUE TITLE
The reproduced results are relatively poor

### ISSUE THREAD

**Issue by liuxingyu123** [xwjabc/hed#49]
Hello, I reproduced the code according to your steps, but the training results are ODS: 0.755, OIS: 0.773, AP: 0.650, which is different from your results. What's the problem?

**Comment by xwjabc** [comment]
Hmmm that is strange. So you simply evaluate my pretrained version (see the command below) and got the low values?
```bash
python hed.py --checkpoint ./data/hed_checkpoint.pt --output ./output-mypretrain --test
cd eval
(echo "data_dir = '../output-mypretrain/test'"; cat eval_edge.m)|matlab -nodisplay -nodesktop -nosplash
```

**Comment by liuxingyu123** [comment]
your pretrained result is OIS:0.788,ODS:0.808,AP:0.840，but my reproduced result is lower,Is it because of the environment? My environment is pytorch1.7, python3.7.

**Comment by xwjabc** [comment]
I see. It is possible due to the environment issue. My previous environment is PyTorch 1.0 + Python 3.6. Let me try to reproduce it with PyTorch 1.7.0 + Python 3.7. Stay tuned.

**Comment by liuxingyu123** [comment]
ok,thank you very much.

**Comment by liuxingyu123** [comment]
hello,i try to reproduce it with pytorch1.0+python3.6 , the result is same on pytorch1.6+python3.7 lower than your OIS:0.788,ODS:0.808,AP:0.840,i follow readme to reproduce .do you have other idea to fix this problem? thank you.

**Comment by liuxingyu123** [comment]
The tested plot diagram is abnormal. Do you know why
![image](https://user-images.githubusercontent.com/59238693/191257275-15c47cf6-1d85-4f59-bed9-d95537cce837.png)

**Comment by liuxingyu123** [comment]
I solved this problem, I found my eval code is wrong, thank you very much.
