### ISSUE TITLE
When I run the following command in pycharm

### ISSUE THREAD

**Issue by peiyunju** [xwjabc/hed#51]
When I run the following command in pycharm   (windows10,python=3.7,torch=1.10,matlab=2020b)
cd eval
(echo "data_dir = '../output/epoch-39-test'"; cat eval_edge.m)|matlab -nodisplay -nodesktop -nosplash
The following issues occur
![1667219169587](https://user-images.githubusercontent.com/103239036/199007571-899fec9b-928d-4044-b72e-d595a41c6c8f.png)

**Comment by JusticeLin** [comment]
Is your problem  solved?I meet some error when using the command ,too.
