### ISSUE TITLE
Question about data preprocessing

### ISSUE THREAD

**Issue by shuangshuangguo** [xwjabc/hed#8]
Hello, could you tell me how to generate the ground-truth edge image? I want to evaluate hed on my own dataset.
For the open BSDS dataset, the ground-truth is described by .mat file.

**Comment by xwjabc** [comment]
You can refer to the structure of the ground-truth .mat file of BSDS dataset:
The .mat file contains one variable: `groundTruth` which is an 1 x k cell matrix (k can be any number >= 1).
Each cell (e.g. `groundTruth{1,1}`) has 2 variables: `Segmentation` and `Boundaries`. You only need to fill the variable `Boundaries`: The shape of the variable is H x W and the value should be 0 or 1 (1 means edge). 
You can use MATLAB or Python (with scipy package) to generate such .mat file.

**Comment by shuangshuangguo** [comment]
Thank you, Now I have the ground-truth file which is similar to .mat file. But I am confused about your generated ground-truth images. When I use cv2.imread() to get the pixel value, I found value > 1. So I want to know how to generate the ground-truth image.
Thank you again.

**Comment by shuangshuangguo** [comment]
Thank you, Now I have the ground-truth file which is similar to .mat file. But I am confused about your generated ground-truth images. When I use cv2.imread() to get the pixel value, I found some value != 255. So I want to know how to generate the ground-truth image.
Thank you again.

**Comment by xwjabc** [comment]
I see. Actually, my BSDS training images are directly ported from the official repository (https://github.com/s9xie/hed), which does not provide the script to augment the original BSDS dataset. You may refer to the augmentation script (https://github.com/SHUCV/SK-LARGE/blob/master/augmentation.m) for a skeleton detection dataset (http://kaiz.xyz/sk-large) which has a similar aim.

**Comment by shuangshuangguo** [comment]
Thank you very much.

**Comment by ZhouCX117** [comment]
@xwjabc hi, the augmentation script you mentioned (https://github.com/SHUCV/SK-LARGE/blob/master/augmentation.m) is not valid, could you give me a favor ?

**Comment by xwjabc** [comment]
Hi @ToBeNormal, you may need to contact the maintainer of the SK-LARGE dataset for such file (see https://kaizhao.net/sk-large).
